version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - configs/db.env
    ports:
      - 5432:5432

